// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Online/CoreOnline.h"
#include "OnlineSubsystemTypes.h"
#include "Interfaces/OnlineIdentityInterface.h"
#include "OnlineSubsystemCognitoTypes.h"
#include "Interfaces/BAOnlineIdentity.h"
#include "BAMultiplayerCoreTypes.h"
THIRD_PARTY_INCLUDES_START
#include "aws/core/Aws.h"
#include "aws/core/client/ClientConfiguration.h"
#include "aws/cognito-idp/CognitoIdentityProviderClient.h"
THIRD_PARTY_INCLUDES_END

class FOnlineSubsystemCognito;
class UBAUser;

/**
 * Info associated with an user account generated by this online service
 */
class ONLINESUBSYSTEMCOGNITO_API FUserOnlineAccountCognito : public FUserOnlineAccount
{

public:

	FUserOnlineAccountCognito(const FString& InUserId = TEXT("")) : UserIdPtr(new FUniqueNetIdCognito(InUserId))
	{
	}

	virtual ~FUserOnlineAccountCognito()
	{
	}

	// FOnlineUser

	virtual TSharedRef<const FUniqueNetId> GetUserId() const override { return UserIdPtr; }
	virtual FString GetRealName() const override { return TEXT("DummyRealName"); }
	virtual FString GetDisplayName(const FString& Platform = FString()) const override { return TEXT("DummyDisplayName"); }
	virtual bool GetUserAttribute(const FString& AttrName, FString& OutAttrValue) const override;
	virtual bool SetUserAttribute(const FString& AttrName, const FString& AttrValue) override;

	// FUserOnlineAccount

	virtual FString GetAccessToken() const override { return TEXT("DummyAuthTicket"); }
	virtual bool GetAuthAttribute(const FString& AttrName, FString& OutAttrValue) const override;

	// FUserOnlineAccountCognito


	/** User Id represented as a FUniqueNetId */
	TSharedRef<const FUniqueNetId> UserIdPtr;

	/** Additional key/value pair data related to auth */
	TMap<FString, FString> AdditionalAuthData;
	/** Additional key/value pair data related to user attribution */
	TMap<FString, FString> UserAttributes;

	UBAUser* BAUser;
};

/**
 * Cognito service implementation of the online identity interface
 */

class ONLINESUBSYSTEMCOGNITO_API FOnlineIdentityCognito : public IOnlineIdentity/*, public IBAOnlineIdentity*/
{


private:

	Aws::SDKOptions AWSOptions;
	std::shared_ptr<Aws::CognitoIdentityProvider::CognitoIdentityProviderClient> s_AmazonCognitoClient;


	/** Cached pointer to owning subsystem */
	FOnlineSubsystemCognito* CognitoSubsystem;

	/** Ids mapped to locally registered users */
	TMap<int32, TSharedPtr<const FUniqueNetId>> UserIds;

	/** Ids mapped to locally registered users */
	TMap<FUniqueNetIdCognito, TSharedRef<FUserOnlineAccountCognito>> UserAccounts;

public:

	FOnSignUpResponse OnSignUpResponse;

	FOnSignUpVerificationResponse OnSignUpVerificationResponse;

public:

	// IOnlineIdentity

	virtual bool Login(int32 LocalUserNum, const FOnlineAccountCredentials& AccountCredentials) override;
	virtual bool Logout(int32 LocalUserNum) override;
	virtual bool AutoLogin(int32 LocalUserNum) override;
	virtual TSharedPtr<FUserOnlineAccount> GetUserAccount(const FUniqueNetId& UserId) const override;
	virtual TArray<TSharedPtr<FUserOnlineAccount> > GetAllUserAccounts() const override;
	virtual TSharedPtr<const FUniqueNetId> GetUniquePlayerId(int32 LocalUserNum) const override;
	virtual TSharedPtr<const FUniqueNetId> CreateUniquePlayerId(uint8* Bytes, int32 Size) override;
	virtual TSharedPtr<const FUniqueNetId> CreateUniquePlayerId(const FString& Str) override;
	virtual ELoginStatus::Type GetLoginStatus(int32 LocalUserNum) const override;
	virtual ELoginStatus::Type GetLoginStatus(const FUniqueNetId& UserId) const override;
	virtual FString GetPlayerNickname(int32 LocalUserNum) const override;
	virtual FString GetPlayerNickname(const FUniqueNetId& UserId) const override;
	virtual FString GetAuthToken(int32 LocalUserNum) const override;
	virtual void RevokeAuthToken(const FUniqueNetId& UserId, const FOnRevokeAuthTokenCompleteDelegate& Delegate) override;
	virtual void GetUserPrivilege(const FUniqueNetId& UserId, EUserPrivileges::Type Privilege, const FOnGetUserPrivilegeCompleteDelegate& Delegate) override;
	virtual FPlatformUserId GetPlatformUserIdFromUniqueNetId(const FUniqueNetId& UniqueNetId) const override;
	virtual FString GetAuthType() const override;


	// IBAOnlineIdentity
	void BAOnloginCompleted(const FBALoginResponse& Response) /*override*/;
	TSharedPtr<FUniqueNetId> BAMakeSharedUniqueID(const FUniqueNetId& PlayerId) /*override*/;
	void SignUp(const FString& Email, const FString& Username, const FString& Password, const FString& RepeatPassword);
	void VerifyCode(const FString& Username, const FString& ConfirmationCode);
	//End: IBAOnlineIdentity

	/**
	 * Constructor
	 *
	 * @param InSubsystem online subsystem being used
	 */
	FOnlineIdentityCognito(FOnlineSubsystemCognito* InSubsystem);

	/**
	 * Destructor
	 */
	virtual ~FOnlineIdentityCognito();


private:

	//TMap<int32, UBAUser*> UsersById;

	/**
	 * Should use the initialization constructor instead
	 */
	FOnlineIdentityCognito() = delete;
};

typedef TSharedPtr<FOnlineIdentityCognito, ESPMode::ThreadSafe> FOnlineIdentityCognitoPtr;